### ISSUE TITLE
still crashing

### ISSUE THREAD

**Issue by iwmo** [VikasSharma707/chatgpt-api-whisper-api-voice-assistant#1]
Hi Vikas,

Thanks for your reply on other thread.
I'm still getting another error and app crashes.

To create a public link, set `share=True` in `launch()`.
/Users/joaoribeiro/Desktop/whisper/venv/lib/python3.11/site-packages/gradio/processing_utils.py:239: UserWarning: Trying to convert audio automatically from int32 to 16-bit int format.
  warnings.warn(warning.format(data.dtype))
<_io.BufferedRandom name='converted_audio.wav'>
Traceback (most recent call last):
  File "/Users/joaoribeiro/Desktop/whisper/venv/lib/python3.11/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joaoribeiro/Desktop/whisper/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1069, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joaoribeiro/Desktop/whisper/venv/lib/python3.11/site-packages/gradio/blocks.py", line 878, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joaoribeiro/Desktop/whisper/venv/lib/python3.11/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joaoribeiro/Desktop/whisper/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/joaoribeiro/Desktop/whisper/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joaoribeiro/Desktop/whisper/main.py", line 37, in transcribe_audio
    voices = engine.getProperty('voices')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joaoribeiro/Desktop/whisper/venv/lib/python3.11/site-packages/pyttsx3/engine.py", line 146, in getProperty
    return self.proxy.getProperty(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joaoribeiro/Desktop/whisper/venv/lib/python3.11/site-packages/pyttsx3/driver.py", line 173, in getProperty
    return self._driver.getProperty(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joaoribeiro/Desktop/whisper/venv/lib/python3.11/site-packages/pyttsx3/drivers/nsss.py", line 69, in getProperty
    return [self._toVoice(NSSpeechSynthesizer.attributesForVoice_(v))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joaoribeiro/Desktop/whisper/venv/lib/python3.11/site-packages/pyttsx3/drivers/nsss.py", line 69, in <listcomp>
    return [self._toVoice(NSSpeechSynthesizer.attributesForVoice_(v))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joaoribeiro/Desktop/whisper/venv/lib/python3.11/site-packages/pyttsx3/drivers/nsss.py", line 64, in _toVoice
    attr['VoiceAge'])
    ~~~~^^^^^^^^^^^^
  File "/Users/joaoribeiro/Desktop/whisper/venv/lib/python3.11/site-packages/objc/_convenience_mapping.py", line 18, in __getitem__objectForKey_
    return container_unwrap(res, KeyError, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joaoribeiro/Desktop/whisper/venv/lib/python3.11/site-packages/objc/_convenience.py", line 134, in container_unwrap
    raise exc_type(*exc_args)
KeyError: 'VoiceAge'


any idea?

thanks

**Comment by VikasSharma707** [comment]
create Virtual environment
Follow the steps:
1.create virtual enviroument
2. install : pip install -r requriments.txt
3. run: python web.py

**Comment by iwmo** [comment]
I did that from first time... but after you said, I repeated. same outcome unfortunately but thanks
